# Change these first
owner: im-parsa # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Portfolio
    url: https://im-parsa.tech
    icon: https://parsa-firoozi.ir/favicon.png
    assignees:
      - im-parsa

status-website:
  metaTags:
    - name: "theme-color"
      content: "#4f40f8"
    - name: "description"
      content: "An automatic and dynamic generated page to show status and services created & hosted on Parsa's Server and Github Pages"
    - name: "twitter:url"
      content: "https://im-parsa.github.io/status/"
    - name: "twitter:title"
      content: "Parsa's Uptime Page"
    - name: "twitter:description"
      content: "An automatic and dynamic generated page to show status and services created & hosted on Parsa's Server and Github Pages"
    - name: "twitter:card"
      content: "summary"
  theme: ocean
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname:  im-parsa.github.io/status/
  baseUrl: /status
  logoUrl: https://parsa-firoozi.ir/favicon.png
  name: Parsa's Uptime Status Page
  introTitle: "**Parsa's Uptime Status Page** - im-parsa"
  introMessage: This page is [generated automaticly](https://github.com/im-parsa/status) to show status and services created & hosted on [im-parsa](https://github.com/im-parsa)'s Server and Github Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://im-parsa.tech
    - title: Instagram
      href: https://www.instagram.com/hello_im_parsa
i18n:
  footer: Made by [im-parsa](https://github.com/im-parsa) - Generated by Upptime
skipDescriptionUpdate: true
skipTopicsUpdate: true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
